name: Notify users based on issue labels

on:
  issues:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - uses: bugobliterator/issue-label-notification-action@master
          with:
             recipients: |
                  AZERTYUIOP=@khancyr
